FROM openjdk:11-slim

# Get arguments from the build command line
ARG version \
    keystore_pass \
    key_pass

ENV VERSION=$version

# Build up the OS
RUN apt-get update \
 && apt-get install -y curl \
                       libtcnative-1

# Make room for the app and capture the version
RUN mkdir /usr/local/registry-api-service \
 && cd /usr/local/registry-api-service \
 && echo ${VERSION} > version.txt

# Copy the data into the building container
COPY LICENSE.md /usr/local/registry-api-service
COPY NOTICE.txt /usr/local/registry-api-service
COPY README.md /usr/local/registry-api-service

# Resources shared with the rest of the world
EXPOSE 443

# Load the local jar file - the config is contained therein
COPY target/registry-api-service-${VERSION}.jar /usr/local/registry-api-service

# TODO: Set-up bind dir for application.properties here...

# Now generate/store the self signed cert.
RUN cd /usr/local/registry-api-service \
 && keytool -genkeypair -keyalg RSA -alias registry -keystore keystore.p12 \
            -storepass $keystore_pass -keypass $key_pass \
            -dname "CN=Unknown" -keysize 2048 -validity 3650 -noprompt \
 && rm -rf /var/lib/apt/lists/*

# Run the sevice by default
WORKDIR /usr/local/registry-api-service

CMD ["java", \
     "-cp", "/usr/local/registry-api-service", \
     "-jar", "/usr/local/registry-api-service/registry-api-service.jar", \
     "gov.nasa.pds.api.engineering.SpringBootMain"]
