# Copyright © 2022, California Institute of Technology ("Caltech").
# U.S. Government sponsorship acknowledged.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# • Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# • Redistributions must reproduce the above copyright notice, this list of
#   conditions and the following disclaimer in the documentation and/or other
#   materials provided with the distribution.
# • Neither the name of Caltech nor its operating division, the Jet Propulsion
#   Laboratory, nor the names of its contributors may be used to endorse or
#   promote products derived from this software without specific prior written
#   permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

version: "3.9"

services:

  # Executes the Registry Loader component, which contains Harvest and Registry Manager
  registry-loader:
    profiles: ["reg-loader"]
    image: ${REG_LOADER_IMAGE}
    environment:
      - ES_URL=${ES_URL}
    volumes:
      - ${HARVEST_CFG_FILE}:/cfg/harvest-config.xml
      - ${HARVEST_DATA_DIR}:/data
    networks:
      - pds

  # Downloads and harvests test data with the Registry loader
  registry-loader-test:
    profiles: [ "reg-loader-test", "pre-api-dev", "integration-test" ]
    image: ${REG_LOADER_IMAGE}
    environment:
      - ES_URL=${ES_URL}
      - RUN_TESTS=true
      - TEST_DATA_URL=${TEST_DATA_URL}
    volumes:
      - ./scripts/registry-loader-waits-for-elasticsearch.sh:/usr/local/bin/registry-loader-waits-for-elasticsearch.sh
    networks:
      - pds
    entrypoint: /usr/local/bin/registry-loader-waits-for-elasticsearch.sh

  # Starts Elasticsearch
  elasticsearch:
    profiles: ["elastic", "services", "pre-api-dev", "integration-test", "big-data", "big-data-integration-test"]
    image: ${ES_IMAGE}
    environment:
      - discovery.type=${ES_DISCOVERY_TYPE}
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - pds

  # Initializes Elasticsearch by creating registry and data dictionary indices by utilizing the Registry Loader
  init-elasticsearch:
    profiles: ["elastic", "big-data", "big-data-integration-test"]
    image: ${REG_LOADER_IMAGE}
    environment:
      - ES_URL=${ES_URL}
    volumes:
      - ./scripts/init-elasticsearch.sh:/usr/local/bin/init-elasticsearch.sh
    networks:
      - pds
    entrypoint: ["bash", "/usr/local/bin/init-elasticsearch.sh"]

  # Starts RabbitMQ
  rabbit-mq:
    profiles: ["rabbitmq", "big-data", "big-data-integration-test"]
    image: rabbitmq:3.9-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - pds

  # Starts the Registry API
  registry-api:
    profiles: ["api", "services", "integration-test", "big-data", "big-data-integration-test"]
    image: ${REG_API_IMAGE}
    ports:
      - "8080:8080"
    volumes:
      - ${REG_API_APP_PROPERTIES_FILE}:/usr/local/registry-api-service/application.properties
      - ./scripts/registry-api-waits-for-elasticsearch.sh:/usr/local/registry-api-service/registry-api-waits-for-elasticsearch.sh
    networks:
      - pds
    command: /usr/local/registry-api-service/registry-api-waits-for-elasticsearch.sh

  # Starts the Registry Harvest Service
  registry-harvest-service:
    profiles: ["big-data-services", "big-data", "big-data-integration-test"]
    image: ${REGISTRY_HARVEST_SERVICE_IMAGE}
    environment:
      - ES_URL=${ES_URL}
    ports:
      - "8005:8005"
    volumes:
      - ${HARVEST_SERVER_CONFIG_FILE}:/cfg/harvest-server.cfg
      - ${HARVEST_DATA_DIR}:/data
    networks:
      - pds

  # Starts the Registry Crawler Service
  registry-crawler-service:
    profiles: ["big-data-services", "big-data", "big-data-integration-test"]
    image: ${REGISTRY_CRAWLER_SERVICE_IMAGE}
    ports:
      - "8001:8001"
    volumes:
      - $CRAWLER_SERVER_CONFIG_FILE:/cfg/crawler-server.cfg
      - ${HARVEST_DATA_DIR}:/data
    networks:
      - pds

  # Executes the Registry Harvest CLI
  registry-harvest-cli:
    profiles: ["registry-harvest-cli", "big-data"]
    image: ${REGISTRY_HARVEST_CLI_IMAGE}
    volumes:
      - ${HARVEST_JOB_CONFIG_FILE}:/cfg/harvest-job-config.xml
      - ${HARVEST_DATA_DIR}:/data
      - ${HARVEST_CLIENT_CONFIG_FILE}:/cfg/harvest-client.cfg
    networks:
      - pds

  # Executes the Registry Harvest CLI with test data
  registry-harvest-cli-test:
    profiles: ["registry-harvest-cli-test", "big-data", "big-data-integration-test"]
    image: ${REGISTRY_HARVEST_CLI_IMAGE}
    environment:
      - RUN_TESTS=true
      - TEST_DATA_URL=${TEST_DATA_URL}
    volumes:
      - ${HARVEST_JOB_CONFIG_FILE}:/cfg/harvest-job-config.xml
      - ${HARVEST_DATA_DIR}:/data
      - ${HARVEST_CLIENT_CONFIG_FILE}:/cfg/harvest-client.cfg
    networks:
      - pds

networks:
  pds:
    driver: bridge
    labels:
      org.label-schema.name: Planetary Data System (PDS)
      org.label-schema.description: Internal bridge network for interprocess communication of services for the PDS
